version: "3.8"
services:
  wsp-campodulce:
    build: .
    container_name: wsp-campodulce-produccion
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env